name: Frequent Workflow

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 5 minutes

jobs:
  frequent-task:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute script
        run: |
          echo "Running task every 5 minutes..."
          # Add your custom commands or scripts here
          echo "Task execution complete."
